[[redirects]]
  from = "/api/*"
  to = "https://gerenciador-projetos-teste.netlify.app/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}